### PR TITLE
fix: add fieldMask for getDevice and listDevices

### LINKED ISSUE #178: Improve FieldMask documentation
This is just a suggestion to improve the docs.

I was trying to use the [`DeviceManagerClient#listDevices`](https://googleapis.dev/nodejs/iot/latest/v1.DeviceManagerClient.html#listDevices) method to get a list of my devices, but I wanted the response to include the `lastHeartbeatTime` field.

According to the docs, I need to add a `fieldMask` to the `listDevices` request. First off, it's pretty hard to figure out what the expected format of `fieldMask` is. There are no examples whatsoever in the docs, all it says is it should be an Object of the same shape as `FieldMask`.

It then links to a [generic explanation on fieldmasks](https://googleapis.dev/nodejs/iot/latest/google.protobuf.html#.FieldMask), which is even more confusing because the examples there are written in in the protobuf definition language.

I finally manage to figure out that one of the expected formats is something like this

```
{ paths: ["name", "id"] }
```

So I proceed to add `lastHeartbeatTime`:

```
{ paths: ["name", "lastHeartbeatTime"] }
```

Which gives me the following error:

> Error: The field 'lastHeartbeatTime' is invalid

That surprised me, because the actual response objects really _do_ contain a `lastHeartbeatTime` field (which is nulled out by default).

I finally find my way to the protobuf definitions, only to find that in protobuf the fields are defined in snake_case. So the following works:

```
{ paths: ["name", "last_heartbeat_time"] }
```

It seems that the node API is automatically changing the casing to camelCase.

All in all there are quite a few mental steps involved to get fieldMasks to work, which are completely unclear from the docs.

### PR DESCRIPTION
**Pull request by gcseh**
Fixes #178

### CODE REVIEW

File: samples/manager/manager.js [hunk 1]
```diff
@@ -449,7 +449,14 @@ const listDevices = async (registryId, projectId, cloudRegion) => {
       registryId
     );
 
-    const [response] = await iotClient.listDevices({parent: parentName});
+    // See full list of device fields: https://cloud.google.com/iot/docs/reference/cloudiot/rest/v1/projects.locations.registries.devices
+    // Warning! Use snake_case field names.
+    const fieldMask = { paths: [ 'id', 'name', 'num_id', 'credentials', 'last_heartbeat_time', 'last_event_time', 'last_state_time', 'last_config_ack_time', 'last_config_send_time', 'blocked', 'last_error_time', 'last_error_status', 'config', 'state', 'log_level', 'metadata', 'gateway_config' ] };
```
Comment (telpirion) [inline samples/manager/manager.js:454]: This is definitely a place where I would break this line up, for example:

```
const fieldMask = {
    paths: [
        'id',
        'name',
        ...
    ]
};
```

You can probably use `prettier` to automatically format it for you.

File: samples/manager/manager.js [hunk 2]
```diff
@@ -620,7 +627,14 @@ const getDevice = async (deviceId, registryId, projectId, cloudRegion) => {
       deviceId
     );
 
-    const [response] = await iotClient.getDevice({name: devicePath});
+    // See full list of device fields: https://cloud.google.com/iot/docs/reference/cloudiot/rest/v1/projects.locations.registries.devices
+    // Warning! Use snake_case field names.
+    const fieldMask = { paths: [ 'id', 'name', 'num_id', 'credentials', 'last_heartbeat_time', 'last_event_time', 'last_state_time', 'last_config_ack_time', 'last_config_send_time', 'blocked', 'last_error_time', 'last_error_status', 'config', 'state', 'log_level', 'metadata', 'gateway_config' ] };
```
Comment (telpirion) [inline samples/manager/manager.js:632]: Same as above, break into additional lines for readability.

**Review by telpirion — APPROVED** [review]
Two small comments, but I would definitely take care of them (to save yourself future linter errors).
